name: Express Server Testing

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  runs_server_tests:
    name: Run server tests
    runs-on: ubuntu-latest

    env:
      DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
      PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
      ENC_KEY: ${{ secrets.ENC_KEY }}
      ENC_IV: ${{ secrets.ENC_IV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CI: true

    steps:
      - name: Clone repo to Actions
        uses: actions/checkout@v3

      - name: Set up NodeJS on Actions computer
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        run: npm install

      - name: Delay for 10 minutes
        run: sleep 600

      - name: Run tests
        run: npm run test-ci
